theme: minima

title: Waah Notes
description: Notes for Android Interviews.

author:
  name: shalatan
  email: shalatan6688@gmail.com
  
show_excerpts: false # set to true to show excerpts on the homepage

minima:
  social_links:
    linkedin: https://www.linkedin.com/in/shashanksingh14/
    github: shalatan